// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcH8EAyEYYvuL3pboAJSAnrHLXr9vO5gs',
    appId: '1:539813466063:web:14f1ba509a100cc61e4cba',
    messagingSenderId: '539813466063',
    projectId: 'my-grad-project-45ddc',
    authDomain: 'my-grad-project-45ddc.firebaseapp.com',
    storageBucket: 'my-grad-project-45ddc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS3qmVYKfesyAH4t1z1X5Sy0LIizH_moo',
    appId: '1:539813466063:android:de26105563f16c471e4cba',
    messagingSenderId: '539813466063',
    projectId: 'my-grad-project-45ddc',
    storageBucket: 'my-grad-project-45ddc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzIBcfzIgjEupnp9xpLNEiapucWu__zm0',
    appId: '1:539813466063:ios:48e7d89ad86795fc1e4cba',
    messagingSenderId: '539813466063',
    projectId: 'my-grad-project-45ddc',
    storageBucket: 'my-grad-project-45ddc.appspot.com',
    iosBundleId: 'com.example.fieldz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzIBcfzIgjEupnp9xpLNEiapucWu__zm0',
    appId: '1:539813466063:ios:ad18a21116def4b61e4cba',
    messagingSenderId: '539813466063',
    projectId: 'my-grad-project-45ddc',
    storageBucket: 'my-grad-project-45ddc.appspot.com',
    iosBundleId: 'com.example.fieldz.RunnerTests',
  );
}
